### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by Demi-Marie** [paritytech/MultiSigil#5]
MultiSigil is currently a command-line tool.  We should provide an API for use by other programs

**Comment by kirushik** [comment]
I would close this as out-of-scope.
The tool is perfect as it is now =)

Jokes aside, but I would prefer "tiny codebase, not feature-complete and maintainable by Dependabot" to "feature-complete, larger codebase and requires manual interventions to fix/test things before updating dependencies".
